import type { Metadata } from "next";
import { Caladea, Tinos, MonteCarlo } from "next/font/google";
import "./globals.css";

const caladea = Caladea({
  variable: "--font-caladea",
  weight: ["400", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

const tinos = Tinos({
  variable: "--font-tinos",
  weight: ["400", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

const script = MonteCarlo({
  variable: "--font-monte",
  weight: ["400"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}
        className={`${caladea.variable} ${tinos.variable} ${script.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
